services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./data:/site/data
      - ./database:/site/database
    environment:
      - DATABASE_URL=sqlite3:/site/database/series.db 
