// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/series": {
            "get": {
                "description": "Retorna una lista de todas las series guardadas en la base de datos",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "series"
                ],
                "summary": "Obtener todas las series",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/main.Series"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Crea una nueva serie con los datos enviados",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "series"
                ],
                "summary": "Crear una nueva serie",
                "parameters": [
                    {
                        "description": "Datos de la nueva serie",
                        "name": "serie",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.Series"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/main.Series"
                        }
                    },
                    "400": {
                        "description": "Datos inválidos",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/series/{id}": {
            "get": {
                "description": "Retorna una serie específica por su ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "series"
                ],
                "summary": "Obtener una serie por ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de la serie",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.Series"
                        }
                    },
                    "400": {
                        "description": "ID inválido",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Serie no encontrada",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "put": {
                "description": "Actualiza la información de una serie existente",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "series"
                ],
                "summary": "Actualizar una serie",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de la serie",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Datos actualizados",
                        "name": "serie",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.Series"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.Series"
                        }
                    },
                    "400": {
                        "description": "ID o JSON inválido",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Serie no encontrada",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "description": "Elimina una serie existente por su ID",
                "tags": [
                    "series"
                ],
                "summary": "Eliminar una serie",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de la serie",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Sin contenido",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "ID inválido",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Serie no encontrada",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/series/{id}/episodeplusone": {
            "patch": {
                "description": "Incrementa en 1 el número de episodios vistos (` + "`" + `lws_episodes` + "`" + `) de una serie específica",
                "tags": [
                    "series"
                ],
                "summary": "Sumar un episodio visto",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de la serie",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Episodio sumado",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "ID inválido",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Serie no encontrada",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Error del servidor",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/series/{id}/status": {
            "patch": {
                "description": "Actualiza el campo ` + "`" + `status` + "`" + ` de una serie con el valor enviado en el cuerpo",
                "tags": [
                    "series"
                ],
                "summary": "Cambiar estado de una serie",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de la serie",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Nuevo estado en formato JSON. Ej: {\\",
                        "name": "status",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Estado actualizado",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "ID inválido o JSON mal formado",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Serie no encontrada",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Error del servidor",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/series/{id}/upvote": {
            "post": {
                "description": "Disminuye el ranking de una serie específica",
                "tags": [
                    "series"
                ],
                "summary": "Votar por una serie (downvote)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de la serie",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Voto aplicado",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "ID inválido",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "main.Series": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "lastEpisodeWatched": {
                    "type": "integer"
                },
                "ranking": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "totalEpisodes": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "API de Series",
	Description:      "Esta API permite manejar información de series, incluyendo episodios vistos, estatus, y votaciones.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
